---
title: "Bitcoin centroid analysis"
output: html_notebook
---
Importing Bitcoin alltime:

```{r}
char_bitcoin_alltime <- read.csv('../data/bitcoin_alltime.csv')
char_bitcoin_alltime <- char_bitcoin_alltime[,2]
bitcoin_alltime = as.double(char_bitcoin_alltime)
idx = 1:length(bitcoin_alltime)

for (i in idx) {
  if (is.na(bitcoin_alltime[i]) || is.nan(bitcoin_alltime[i])) {
    bitcoin_alltime[i] <- bitcoin_alltime[i-1]
  }
}
sprintf("Length: %d",length(bitcoin_alltime))
plot(idx,bitcoin_alltime,type='l')
```
Now we look at the clusters of the four data matrizes (sts_target,sts_opposed,whole_target,whole_opposed) calculated for different r,k,w values for the Bitcoin as target time series.
```{r}
source("random_walk.R")
n <- 1
r <- 10

#ks <- c(3,5,7,11)
#ws <- c(8,16,32)

k <- 5
w <- 8

norm_methods <- c("none","center", "scale", "range");
dist_metrics <- c("eukl")
cluster_algos <- c("kmeans","agglo","gmm")


cluster_algo <- cluster_algos[1]
norm_method <- norm_methods[3]
dist_metric <- dist_metrics[1]
reduced_sampling <- TRUE
#not working yet
dim_red <- FALSE
unify <- TRUE

current_ts <- bitcoin_alltime
opposing_ts <- create_random_walk(current_ts)
#opposing_ts <- bitcoin_alltime


meaningfulness_sts <- 0
meaningfulness_whole <- 0
  
sts_ts_matrix <- to_sts_matrix(current_ts, w)
sts_ts_matrix <- scale_feature_matrix(sts_ts_matrix, norm_method)
  
whole_ts_matrix <- to_random_sampling_matrix(current_ts, w, reduced_sampling)
whole_ts_matrix <- scale_feature_matrix(whole_ts_matrix, norm_method)
  
sts_random_matrix <- to_sts_matrix(opposing_ts, w)
sts_random_matrix <- scale_feature_matrix(sts_random_matrix, norm_method)
  
whole_random_matrix <- to_random_sampling_matrix(opposing_ts, w, reduced_sampling)
whole_random_matrix <- scale_feature_matrix(whole_random_matrix, norm_method)
  
if (dim_red && w>8) {
  
}
  
for (z in 1:n) {
  sts_ts_centers <- array(0, c(k,w,r))
  sts_random_centers <- array(0, c(k,w,r))
    
  whole_ts_centers <- array(0, c(k,w,r))
  whole_random_centers <- array(0, c(k,w,r))
    
  for (i in 1:r) {
    sts_ts_centers[,,i] <- cluster_functions(sts_ts_matrix,k,cluster_algo,unify)
    whole_ts_centers[,,i] <- cluster_functions(whole_ts_matrix,k,cluster_algo,unify)
    sts_random_centers[,,i] <- cluster_functions(sts_random_matrix,k,cluster_algo,unify)
    whole_random_centers[,,i] <- cluster_functions(whole_random_matrix,k,cluster_algo,unify)
  }
  cm_sts <- cluster_meaningfulness(sts_ts_centers, sts_random_centers, dist_metric)
  cm_whole <- cluster_meaningfulness(whole_ts_centers, whole_random_centers, dist_metric)
    
  meaningfulness_sts <- meaningfulness_sts + cm_sts
  meaningfulness_whole <- meaningfulness_whole + cm_whole
}
meaningfulness_sts <- meaningfulness_sts/n
meaningfulness_whole <- meaningfulness_whole/n
 
```