---
title: "R Notebook"
output: html_notebook
---

### Load scatter data set

```{r}
tab_samples_2000 <- read.csv('../data/scatter_samples_2000.csv')[,2:3]
tab_samples_20 <- read.csv('../data/scatter_samples_20.csv')[,2:3]
print(plot(tab_samples_2000[,1],tab_samples_2000[,2],xlab='x',ylab='y'))
print(plot(tab_samples_20[,1],tab_samples_20[,2],xlab='x',ylab='y'))
samples_2000 <- apply(as.matrix.noquote(tab_samples_2000),2,as.numeric)
samples_20 <- apply(as.matrix.noquote(tab_samples_20),2,as.numeric)
```

### Running KMeans on both sampling sets two times and visualising clusters
First on data set with 2000 points.

```{r}
km_1 <- kmeans(samples_2000,2)
km_2 <- kmeans(samples_2000,2)

centroids_1 <- km_1$centers
centroids_2 <- km_2$centers

labels_1 <- km_1$cluster
labels_2 <- km_2$cluster

occur_1_0 <- 0
occur_1_1 <- 0
for (la in labels_1) {
    if (la == 1) {
        occur_1_0 <- occur_1_0 + 1
    } else {
        occur_1_1 <- occur_1_1 + 1
    }
}

occur_2_0 <- 0
occur_2_1 <- 0
for (la in labels_2) {
    if (la == 1) {
        occur_2_0 <- occur_2_0 + 1
    } else {
        occur_2_1 <- occur_2_1 + 1
    }
}

group_1_0 <- array(0,c(occur_1_0,2))
group_1_1 <- array(0,c(occur_1_1,2))

group_2_0 <- array(0,c(occur_2_0,2))
group_2_1 <- array(0,c(occur_2_1,2))

c_1 <- 1
c_2 <- 1
for (i in 1:length(labels_1)) {
    if (labels_1[i] == 1) {
        group_1_0[c_1,] <- samples_2000[i,]
        c_1 <- c_1+1
    } else {
        group_1_1[c_2,] <- samples_2000[i,]
        c_2 <- c_2+1
    }
}

c_1 <- 1
c_2 <- 1
for (i in 1:length(labels_2)) {
    if (labels_2[i] == 1) {
        group_2_0[c_1,] <- samples_2000[i,]
        c_1 <- c_1+1
    } else {
        group_2_1[c_2,] <- samples_2000[i,]
        c_2 <- c_2+1
    }
}

plot(samples_2000[,1],samples_2000[,2],col='white',xlab='x',ylab='y',main='First run of KMeans')
points(group_1_0[,1],group_1_0[,2],col='blue')
points(group_1_1[,1],group_1_1[,2],col='red')
points(centroids_1[,1],centroids_1[,2],col='black',pch='+',cex=2)

plot(samples_2000[,1],samples_2000[,2],col='white',xlab='x',ylab='y',main='Second run of KMeans')
points(group_2_0[,1],group_2_0[,2],col='blue')
points(group_2_1[,1],group_2_1[,2],col='red')
points(centroids_2[,1],centroids_2[,2],col='black',pch='+',cex=2)

```
Now on data set with just 20 points.

```{r}
km_1 <- kmeans(samples_20,2)
km_2 <- kmeans(samples_20,2)

centroids_1 <- km_1$centers
centroids_2 <- km_2$centers

labels_1 <- km_1$cluster
labels_2 <- km_2$cluster

occur_1_0 <- 0
occur_1_1 <- 0
for (la in labels_1) {
    if (la == 1) {
        occur_1_0 <- occur_1_0 + 1
    } else {
        occur_1_1 <- occur_1_1 + 1
    }
}

occur_2_0 <- 0
occur_2_1 <- 0
for (la in labels_2) {
    if (la == 1) {
        occur_2_0 <- occur_2_0 + 1
    } else {
        occur_2_1 <- occur_2_1 + 1
    }
}

group_1_0 <- array(0,c(occur_1_0,2))
group_1_1 <- array(0,c(occur_1_1,2))

group_2_0 <- array(0,c(occur_2_0,2))
group_2_1 <- array(0,c(occur_2_1,2))

c_1 <- 1
c_2 <- 1
for (i in 1:length(labels_1)) {
    if (labels_1[i] == 1) {
        group_1_0[c_1,] <- samples_20[i,]
        c_1 <- c_1+1
    } else {
        group_1_1[c_2,] <- samples_20[i,]
        c_2 <- c_2+1
    }
}

c_1 <- 1
c_2 <- 1
for (i in 1:length(labels_2)) {
    if (labels_2[i] == 1) {
        group_2_0[c_1,] <- samples_20[i,]
        c_1 <- c_1+1
    } else {
        group_2_1[c_2,] <- samples_20[i,]
        c_2 <- c_2+1
    }
}

plot(samples_20[,1],samples_20[,2],col='white',xlab='x',ylab='y',main='First run of KMeans')
points(group_1_0[,1],group_1_0[,2],col='blue')
points(group_1_1[,1],group_1_1[,2],col='red')
points(centroids_1[,1],centroids_1[,2],col='black',pch='+',cex=2)

plot(samples_20[,1],samples_20[,2],col='white',xlab='x',ylab='y',main='Second run of KMeans')
points(group_2_0[,1],group_2_0[,2],col='blue')
points(group_2_1[,1],group_2_1[,2],col='red')
points(centroids_2[,1],centroids_2[,2],col='black',pch='+',cex=2)
```