---
title: "Bitcoin centroid analysis"
output: html_notebook
---
Importing S&P 500 Daily time series:

```{r}
spx <- read.csv('../data/spx_daily_11-21.csv')
spx <- rev(spx[,2])
idx = 1:length(spx)
#sprintf("Length: %d",length(spx))
#plot(idx,spx,type='l')
```

Now we look at the clusters of the four data matrizes (sts_target,sts_opposed,whole_target,whole_opposed) calculated for different r,k,w values for the S&P as target time series.
```{r}
source("random_walk.R")
source("ts_processing.R")
source("distance_measures.R")
source("meaningfulness_functions.R")
source('scale_feature_matrix.R')
source("cluster_functions.R")
library(caret)

###################################
n <- 1
r <- 10

#ks <- c(3,5,7,11)
#ws <- c(8,16,32)

k <- 3
w <- 8

cluster_algo <- cluster_algos[3]
unify <- TRUE
##################################################

norm_methods <- c("none","center", "scale", "range");
dist_metrics <- c("eukl")
cluster_algos <- c("kmeans","agglo","gmm")

norm_method <- norm_methods[3]
dist_metric <- dist_metrics[1]
reduced_sampling <- TRUE
dim_red <- TRUE
seed_ <- 0

target_ts <- spx
opposing_ts <- create_random_walk(target_ts, seed_)


meaningfulness_sts <- 0
meaningfulness_whole <- 0
  
sts_target_matrix <- to_sts_matrix(target_ts, w)
sts_target_matrix <- scale_feature_matrix(sts_target_matrix, norm_method)
  
sts_opposing_matrix <- to_sts_matrix(opposing_ts, w)
sts_opposing_matrix <- scale_feature_matrix(sts_opposing_matrix, norm_method)
  
whole_target_matrix <- to_random_sampling_matrix(target_ts, w, reduced_sampling, seed_)
whole_target_matrix <- scale_feature_matrix(whole_target_matrix, norm_method)

whole_opposing_matrix <- to_random_sampling_matrix(opposing_ts, w, reduced_sampling, seed_)
whole_opposing_matrix <- scale_feature_matrix(whole_opposing_matrix, norm_method)
  
  if (dim_red) {
    sts_target_matrix <- dim_reduction(sts_target_matrix, 0.9)
    sts_opposing_matrix <- dim_reduction(sts_opposing_matrix, 0.9)
    
    whole_target_matrix <- dim_reduction(whole_target_matrix, 0.9)
    whole_opposing_matrix <- dim_reduction(whole_opposing_matrix, 0.9)
  }
  
  w_sts <- min(size(sts_target_matrix)[2], size(sts_opposing_matrix)[2])
  w_whole <- min(size(whole_target_matrix)[2], size(whole_opposing_matrix)[2])
  
  
sts_target_matrix <- sts_target_matrix[,1:w_sts]
sts_opposing_matrix <- sts_opposing_matrix[,1:w_sts]
  
whole_target_matrix <- whole_target_matrix[,1:w_whole]
whole_opposing_matrix <- whole_opposing_matrix[,1:w_whole]
  
  
for (z in 1:n) {
  sts_target_centers <- array(0, c(k,w_sts,r))
  sts_opposing_centers <- array(0, c(k,w_sts,r))
    
  whole_target_centers <- array(0, c(k,w_whole,r))
  whole_opposing_centers <- array(0, c(k,w_whole,r))
    
  for (i in 1:r) {
    sts_target_centers[,,i] <- cluster_functions(sts_target_matrix,k,cluster_algo,unify)
    sts_opposing_centers[,,i] <- cluster_functions(sts_opposing_matrix,k,cluster_algo,unify)
      
    whole_target_centers[,,i] <- cluster_functions(whole_target_matrix,k,cluster_algo,unify)
    whole_opposing_centers[,,i] <- cluster_functions(whole_opposing_matrix,k,cluster_algo,unify)
  }

  print('STS')  
  meaningfulness_sts <- meaningfulness_sts + cluster_meaningfulness(sts_target_centers, sts_opposing_centers, dist_metric)
  print('~~~~~~~~~')
  print('WHOLE')
  meaningfulness_whole <- meaningfulness_whole + cluster_meaningfulness(whole_target_centers, whole_opposing_centers, dist_metric)
  }
meaningfulness_sts <- meaningfulness_sts / n
meaningfulness_whole <- meaningfulness_whole / n


#print('--------------------------------------------------------------------------')    
#print('STS target centers:')
#print('')
#print(sts_target_centers)
#print('--------------------------------------------------------------------------')
#print('STS opposing centers:')
#print('')
#print(sts_opposing_centers)
#print('--------------------------------------------------------------------------')
#print('Whole target centers:')
#print('')
#print(whole_target_centers)
#print('--------------------------------------------------------------------------')
#print('Whole opposing centers:')
#print('')
#print(whole_opposing_centers)
#print('--------------------------------------------------------------------------')
#print('')
#print(paste('sts meaning: ',(meaningfulness_sts/n)))
#print(paste('whole meaning: ',(meaningfulness_whole/n)))



###### visualize ######
n_comp <- 2

pca_sts_target_centers <- array(0,c(k,n_comp,r))
pca_sts_opposing_centers <- array(0,c(k,n_comp,r))
pca_whole_target_centers <- array(0,c(k,n_comp,r))
pca_whole_opposing_centers <- array(0,c(k,n_comp,r))

#pca_sts_target_var = np.zeros((r,k,n_comp))
#pca_sts_opposing_var = np.zeros((r,k,n_comp))
#pca_whole_target_var = np.zeros((r,k,n_comp))
#pca_whole_opposing_var = np.zeros((r,k,n_comp))
    
for (i in 1:r) {
  
  
    pca_sts_target <- prcomp(t(sts_target_centers[,,i]), rank=n_comp)
    pca_sts_opposing <- prcomp(t(sts_opposing_centers[,,i]), rank=n_comp)
    pca_whole_target <- prcomp(t(whole_target_centers[,,i]), rank=n_comp)
    pca_whole_opposing <- prcomp(t(whole_opposing_centers[,,i]), rank=n_comp)
    
    #pca_sts_target_var[i] = pca_sts_target.explained_variance_ratio_
    #pca_sts_opposing_var[i] = pca_sts_opposing.explained_variance_ratio_
    #pca_whole_target_var[i] = pca_whole_target.explained_variance_ratio_
    #pca_whole_opposing_var[i] = pca_whole_opposing.explained_variance_ratio_
       
    pca_sts_target_centers[,,i] <- pca_sts_target$rotation
    pca_sts_opposing_centers[,,i] <- pca_sts_opposing$rotation
    pca_whole_target_centers[,,i] <- pca_whole_target$rotation
    pca_whole_opposing_centers[,,i] <- pca_whole_opposing$rotation
}

#print('--------------------------------------------------------------------------')    
#print('STS target centers:')
#print('')
#print(pca_sts_target_centers)
#print('____')
#print(pca_sts_target_var)
#print('--------------------------------------------------------------------------')
#print('STS opposing centers:')
#print('')
#print(pca_sts_opposing_centers)
#print('____')
#print(pca_sts_opposing_var)
#print('--------------------------------------------------------------------------')
#print('Whole target centers:')
#print('')
#print(pca_whole_target_centers)
#print('____')
#print(pca_whole_target_var)
#print('--------------------------------------------------------------------------')
#print('Whole opposing centers:')
#print('')
#print(pca_whole_opposing_centers)
#print('____')
#print(pca_whole_opposing_var)
#print('--------------------------------------------------------------------------')
#print('')


colors = c('black','magenta','cyan','red','green','blue','orange','lightblue','pink','purple')


plot(0,0)
for (i in 1:r) {
  for (v in 1:k) {
    #points(pca_sts_target_centers[v,1,i],pca_sts_target_centers[v,2,i])
    arrows(0,0,pca_sts_target_centers[v,1,i],pca_sts_target_centers[v,2,i], col = colors[i])
  }
}

plot(0,0)
for (i in 1:r) {
  for (v in 1:k) {
    #points(pca_sts_target_centers[v,1,i],pca_sts_target_centers[v,2,i])
    arrows(0,0,pca_whole_target_centers[v,1,i],pca_whole_target_centers[v,2,i], col = colors[i])
  }
}


plot(0,0)
for (i in 1:r) {
  for (v in 1:k) {
    #points(pca_sts_target_centers[v,1,i],pca_sts_target_centers[v,2,i])
    arrows(0,0,pca_sts_target_centers[v,1,i],pca_sts_target_centers[v,2,i], col = 'black')
  }
}
for (i in 1:r) {
  for (v in 1:k) {
    #points(pca_sts_target_centers[v,1,i],pca_sts_target_centers[v,2,i])
    arrows(0,0,pca_sts_opposing_centers[v,1,i],pca_sts_opposing_centers[v,2,i], col = 'red')
  }
}

plot(0,0)
for (i in 1:r) {
  for (v in 1:k) {
    #points(pca_sts_target_centers[v,1,i],pca_sts_target_centers[v,2,i])
    arrows(0,0,pca_whole_target_centers[v,1,i],pca_whole_target_centers[v,2,i], col = 'black')
  }
}
for (i in 1:r) {
  for (v in 1:k) {
    #points(pca_sts_target_centers[v,1,i],pca_sts_target_centers[v,2,i])
    arrows(0,0,pca_whole_opposing_centers[v,1,i],pca_whole_opposing_centers[v,2,i], col = 'red')
  }
}
```